services:
  ffmpeglab:
    image: ffmpeglab/ide:main
    ports:
      - "8080:8080"
    environment:
      - FFMPEGLAB_HOST=http://localhost:8080/webapp/
      - FFMPEGLAB_API=http://localhost:3000
      - EVOLU_DB_HOST=http://localhost:4000
      - EVOLU_DB_NAME=ffmpeglab
      - PEXELS_API_HOST=https://pexels.starpy.me/
      - PUBLIC_HOST=https://localhost:8080/
      - SUPABASE_HOST=https://office.starpy.me
      - SUPABASE_ANON_KEY=123456789qwerty

  evolu:
    image: evoluhq/evolu:pr-5
    ports:
      - "4000:4000"