upstream api {
    server ${FFMPEGLAB_API_FQDN};
}

upstream platform {
    server ${FFMPEGLAB_PLATFORM_FQDN};
}

upstream supabase {
    server ${SUPABASE_FQDN};
}

server { 
 listen ${FFMPEGLAB_UI_PORT};
 server_name frontend;
 root /usr/share/nginx/html;
 add_header cross-origin-embedder-policy "require-corp";
 add_header cross-origin-opener-policy "cross-origin";
 add_header cross-origin-resource-policy "cross-origin";

 location / {
   try_files $${ESCAPED_URI} /webapp/index.html;
 }

 location /webapp/ {
   try_files $${ESCAPED_URI} /webapp/index.html;
 }

 location = /config.json {
   try_files $${ESCAPED_URI} $${ESCAPED_URI}/ /webapp/config.json;
 }

 location = /templates.json {
   try_files $${ESCAPED_URI} $${ESCAPED_URI}/ /webapp/templates.json;
 }

  location /auth/ {
      proxy_pass http://supabase;
  }

  location /rest/ {
      proxy_pass http://supabase;
  }

  location /storage/ {
      proxy_pass http://supabase;
  }

  location /platform/ {
      proxy_pass http://platform;
  }

  location /api {
      proxy_pass http://api;
  }

  location /renders/ {
      proxy_pass http://api;
  }

  location /files/ {
      proxy_pass http://api;
  }

  location /pipelines/ {
      proxy_pass http://api;
  }
}